### ISSUE TITLE
The image is not showing in the live spec

### ISSUE THREAD

**Issue by kenchris** [w3c/accelerometer#17]
:(

**Comment by alexshalamov** [comment]
@anssiko Looks like published specs were published without images. Is there a way to fix it?

**Comment by anssiko** [comment]
It seems [bikeshed echidna][1] does not automatically publish image resources? I believe we need to define the image resources in [`BSPublishAdditionalFiles`][2] and publish again (haven't used this feature myself, just learned about it by reading the docs).

Ping @tabatkins @dontcallmedom to confirm how to fix.

Problem description:

TR spec published at:

https://www.w3.org/TR/2017/WD-accelerometer-20170411/

... has external image resources that were not automatically published, are 404:

https://www.w3.org/TR/2017/WD-accelerometer-20170411/accelerometer_coordinate_system.svg
https://www.w3.org/TR/2017/WD-accelerometer-20170411/accelerometer_coordinate_system.png

TR spec published with `bikeshed echidna` as follows:

```
bikeshed --force echidna \
         --u USERNAME \
         --p PASSWORD \
         --d https://lists.w3.org/Archives/Public/public-device-apis/2017Apr/att-0013/minutes-2017-04-06.html#resolution02 \
         --md-status=WD index.bs
```

Where `index.bs` is:

https://github.com/w3c/accelerometer/blob/WD-accelerometer-20170411/index.bs


[1]: https://tabatkins.github.io/bikeshed/#cli-echidna
[2]: https://tabatkins.github.io/bikeshed/#echidna-hooks

**Comment by dontcallmedom** [comment]
if I read the docs correctly, I think moving the images to a folder named `images` should have the desired effect without having to maintain a dedicated extension.

**Comment by anssiko** [comment]
Thanks @dontcallmedom, moving image files to images directory indeed fixed it:

https://www.w3.org/TR/accelerometer/

**Comment by dontcallmedom** [comment]
@anssiko I believe the same needs to be done for the two other sensor API fwiw

**Comment by anssiko** [comment]
@dontcallmedom, I just fixed those as well:

https://www.w3.org/TR/gyroscope/
https://www.w3.org/TR/magnetometer/
