### ISSUE TITLE
Normative reference to WebIDL-1 is missing

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/accelerometer#2]

**Comment by marcoscaceres** [comment]
Please don't reference WebIDL-1.

**Comment by dontcallmedom** [comment]
you mean we should reference the [editors draft of WebIDL](http://heycam.github.io/webidl/) instead? (that's fine with me)

**Comment by marcoscaceres** [comment]
Yes please 👍

**Comment by dontcallmedom** [comment]
Closed by bdc56b83821f919fc8c69a2f56c19b3e4c609690
