### ISSUE TITLE
Why unrestricted double for acceleration readings?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/accelerometer#23]
When the spec was [switched from separate reading interface to include it in the main one](https://github.com/w3c/accelerometer/commit/a1b7d8584615f4c6031f7402f10cbd115ba9a91f), the types of the `x`, `y`, `z` attributes were switched to `**unrestricted** double` - what is the reasoning behind the change? I didn't find anything related to `Infinity` in the spec, nor did I easily find any supporting model consideration in the generic sensor spec, nor in the motion sensors spec.

if there is a good reason, I think it should be documented, possibly in the 3 docs; if there isn't,

**Comment by alexshalamov** [comment]
@dontcallmedom Good point, there are no practical reasons to keep `unrestricted double`, as there are no sensors that could measure physical properties of +-Infinity magnitude. We should use double.

@pozdnyakov wdyt?

**Comment by pozdnyakov** [comment]
Think it was supposed to mean "unset value" but now the reading properties are nullable so no need to keep them `unrestricted`.

**Comment by pozdnyakov** [comment]
Think same applies to other concrete sensor classes (Gyroscope, Magnetometer, ..)
