### ISSUE TITLE
includeGravity parameter turns low-level sensor into high-level fused one. 

### ISSUE THREAD

**Issue by tobie** [w3c/accelerometer#3]
Would suggest having two separate interfaces here. One for the low-level accelerator sensor, and the other one for a fused, higher-level gravity-less acceleration (which might also rely on the gyroscope, etc.).

These two have different use cases and should have different APIs to reflect that.

**Comment by anssiko** [comment]
@alexshalamov @riju Could you investigate the use cases for both? We should discuss your findings at TPAC latest. Also, how do the platform APIs (e.g. Android, iOS, Windows) handle the separation?

**Comment by tobie** [comment]
Main use case here is for devs to be aware as to whether they're getting fused or raw data (for latency/perf reasons). Android makes clear distinctions between these.

**Comment by alexshalamov** [comment]
Windows provides generic interface for Accelerometer, developers can choose what type of acceleration readings they need. There is no way to find out whether data is fused or raw.
https://msdn.microsoft.com/en-us/library/windows/apps/mt759596.aspx

On Android, due to design of the Sensor Framework, developers can select acceleration / linear acceleration through type of the sensor. Linear acceleration readings can be fused in SW or can be provided by HW, thus, there is no way to find whether data is raw.

I would prefer to keep interface as is, since it resembles other platform APIs.
Moreover, linear acceleration readings can be provided by HW.

**Comment by tobie** [comment]
That will require rewriting large portions of the generic sensor spec if you want consistent APIs across sensor types.

I'm not sure which approach is the best, but this one isn't consistent with what the GS framework describes.

Iirc, Android has a raw accelerometer data type and so does iOS.

**Comment by tobie** [comment]
One of the main reasons for GS is to disambiguate these issues. It's a shame if the only thing it provides is an alternate, differently inconsistent API. So please either abide by the directives in GS or fix them. :)

**Comment by alexshalamov** [comment]
> That will require rewriting large portions of the generic sensor spec if you want consistent APIs across sensor types.

Could you please tell what part should be rewritten?
If I split interface to AcceleromterSensor and LinearAcceleration how would it help if LinearAcceleration reading is provided by HW?
Moreover, LinearAcceleration sensor would still be derived from Sensor interface, therefore, large portion of Sensor spec should be rewritten, right?

**Comment by tobie** [comment]
Sorry for the terseness, btw. Thumbtyping this while feeding 3 kids about to go back to school.

**Comment by tobie** [comment]
[Section 6 (Concepts)](https://w3c.github.io/sensors/#concepts) and [Section 10 (Extensibility)](https://w3c.github.io/sensors/#extensibility) are the key ones here.

The differentiation made between low and high-level sensors in GS aren't to do with sensor fusion (though generally, most high-level sensors are fused), but about whether the Sensor object describes a kind of physical sensor (e.g. a pressure barometer) or the kind of data you get out of it (e.g. altitude), _regardless of by which mean you actually get that data (in the case of altitude, it could be using a pressure barometer or GPS for example). _(As a sidenote, whether fusion happens are the SF or HW level is irrelevant for this classification.)_

With that distinction in mind, LinearAcceleration would fall in the high-level sensor category (there's fusion going on between a gyroscope and an accelerometer, you're describing the kind of data you get and not the means by which you get it, that data could be obtained through different means, albite with much less precision, e.g. extrapolating from GPS readings).

So in the accelerometer case, the only thing the `Accelerometer` sensor object should provide is raw data accelerometer output including gravity. Note that some platforms (e.g. Android) do offer a smoothed out output for certain sensors (e.g. gyroscope is calibrated for drift), so it might make sense in that case to offer that as an option on the `Gyroscope` object (e.g. `new Gyroscope({ correctForDrift: true });`), again defaulting to raw output.

Note that I'm more than happy to have this distinction re-discussed and modified, but, again, this needs to be done at the GS level, so all extension spec have the same understanding and apply this similarly.

**Comment by alexshalamov** [comment]
Thanks for clarification, but as I mentioned before,  linear acceleration readings can be provided by hw (same accelerometer imu) without doing sensor fusion in SW. Therefore, new Accelerometer({includeGravity: false});  is similar to new Gyroscope({ correctForDrift: true });

If we make separate LinearAccelerationSensor interface and claim that its data is fused from accelerometer and gyro, it would be misleading and incorrect.

**Comment by tobie** [comment]
> Thanks for clarification, but as I mentioned before, linear acceleration readings can be provided by hw (same accelerometer imu) without doing sensor fusion in SW.

Yes, that's because there's a sensor hub that contains both a gyroscope and an accelerometer and uses the output of both of them together to calculate linear acceleration through sensor fusion. In the process it provides a completely different data source.

This contrasts with correcting drift on a a gyroscope which more akin to dynamic calibration (i.e. using output of other sensors to provide a more precise measurement) than sensor fusion (combining different sensors to provide a new kind of data).

That said, it might be more appropriate to distinguish `Gyroscope` from `AngularVelocity` (dynamically calibrated output of a gyroscope).

**Comment by tobie** [comment]
This should really be three APIs here: the low-level `Accelerometer` API and the high-level `Gravity` and `LinearAcceleration` APIs.

**Comment by tobie** [comment]
Incidentally, that's the distinction Android makes. And iOS does roughly the same thing (it bundles gravity and linear acceleration, which it calls user acceleration, in what it calls device motion data, and keeps un-fused accelerometer data separate).

**Comment by anssiko** [comment]
Agreed with @alexshalamov that split into interfaces is the way to go, PR to follow tomorrow.

**Comment by anssiko** [comment]
Are we fine with `Accelerometer`, `LinearAccelerometer`, and `GravitySensor` as the names?

**Comment by tobie** [comment]
I don't really have an opinion on this topic for now. I think clarity will emerge from the research work for the motion sensor spec.

**Comment by alexshalamov** [comment]
@anssiko Thanks for feedback Anssi, I'm +1 for splitting the interface. I will create PR today or later tomorrow, if I would need to draw some explanatory graphics, might take bit more time.

**Comment by anssiko** [comment]
As @tobie mentioned, Android docs note the following high-level ones:

* [Using the Linear Accelerometer][1]
* [Using the Gravity Sensor][2]

[1]: https://developer.android.com/guide/topics/sensors/sensors_motion.html#sensors-motion-linear
[2]: https://developer.android.com/guide/topics/sensors/sensors_motion.html#sensors-motion-grav
