### ISSUE TITLE
define normative privacy mitigation

### ISSUE THREAD

**Issue by samuelweiler** [w3c/accelerometer#57]
Rather than duck by pointing at others' suggestions ("The [TOUCHSIGNATURES] and [ACCESSORY] research papers propose that implementations can ..."), define normative privacy mitigations in this spec.

Here are some of the TAG's and PING's guidance arguing for this:
https://www.w3.org/blog/2019/06/privacy-anti-patterns-in-standards/
https://www.w3.org/blog/TAG/2019/09/11/security-and-privacy-for-our-times/

**Comment by reillyeon** [comment]
Discussed at the TPAC 2024 F2F:

We have normative mitigations in [DEVICE-ORIENTATION] which can be ported to this specification.
